## Ejercicio final
En este ejercicio tiene un conjunto de datos generado de forma artificial, deberá aplicar los conceptos vistos durante las dos primeras sesiones del curso

In [2]:
# Librerias necessarias

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.datasets import make_classification

In [3]:
# Importamos los datos
dataset, classes = make_classification(n_samples=np.random.randint(200,250), n_features=6, n_informative=2, n_redundant=0, n_repeated=0, n_classes=4, n_clusters_per_class=1,  random_state=33)

**Describe el dataset**

¿Cuantas características tiene?
¿Cuantas observaciones?


Caracteristicas = 6
Observaciones = Entre 200 y 250 de manera aleatoria

### Selección
    1.Realiza una selección que tenga todas las filas pero sólo las columnas pares
    2.Realiza una selección que sea el resultado de seleccionar las primeras 10 filas
    3.Realiza una selección  que sea el resultado de seleccionar las últimas 10 filas
    4.Realiza una selección  que sea el resultado de seleccionar  10 filas de forma aleatoria
    5.Realiza una selección de las columnas 3 a la 5 y de las filas 150 a la 160

In [4]:
#1
print(dataset)
dataset[:,1::2]

[[-0.30563994  0.9048432   0.09559884 -0.46808067 -0.78734376 -0.95401056]
 [ 0.9417809   0.54846794  0.00598514  0.57355669 -0.23833054  0.44110563]
 [-0.10763667  0.77699405  0.7516328  -0.79516681 -0.61475792  0.00646073]
 ...
 [-0.59851449  1.19534596 -0.55339663  1.34504259 -1.37909873  1.01356087]
 [ 0.3356252   1.36121216 -0.83412562 -0.82638094  1.80554678 -0.42855539]
 [-0.30567252 -1.00850113  0.16828318  0.84217855  0.32498442 -0.53410072]]


array([[ 0.9048432 , -0.46808067, -0.95401056],
       [ 0.54846794,  0.57355669,  0.44110563],
       [ 0.77699405, -0.79516681,  0.00646073],
       [ 1.7982106 , -0.3154107 ,  0.02566972],
       [-2.62558364,  0.09579144, -1.22959752],
       [-0.99415882,  0.73368313,  0.6372042 ],
       [-1.30227117,  0.28972556,  0.60667898],
       [ 1.17572876,  0.39067803,  1.43947028],
       [-1.41315494,  0.84391135,  0.79696687],
       [-1.21697346,  0.11842104,  1.42521716],
       [ 1.12797664,  1.01217186,  1.40482141],
       [-0.7900613 ,  0.3058683 ,  0.7470859 ],
       [-0.8698975 ,  0.5676924 ,  0.78001725],
       [ 0.77192835, -1.56902316, -0.55044309],
       [-1.92541983,  1.01871512, -1.87208957],
       [ 1.28143691,  0.27176425,  0.82061785],
       [-0.96424113,  1.0410937 ,  0.24072823],
       [-1.13254619, -1.15522429, -0.64710833],
       [-0.48161977, -0.25996059, -0.83081899],
       [ 0.78327064, -0.69918998,  0.25068953],
       [ 0.65995179,  0.03587425, -1.067

In [5]:
#2
dataset[:10,:]

array([[-0.30563994,  0.9048432 ,  0.09559884, -0.46808067, -0.78734376,
        -0.95401056],
       [ 0.9417809 ,  0.54846794,  0.00598514,  0.57355669, -0.23833054,
         0.44110563],
       [-0.10763667,  0.77699405,  0.7516328 , -0.79516681, -0.61475792,
         0.00646073],
       [-1.16995166,  1.7982106 , -0.15734085, -0.3154107 ,  0.33715027,
         0.02566972],
       [-1.02445745, -2.62558364, -1.18426909,  0.09579144, -2.94374921,
        -1.22959752],
       [-1.45785067, -0.99415882, -0.27469436,  0.73368313,  0.67776491,
         0.6372042 ],
       [-0.03334746, -1.30227117, -0.26770643,  0.28972556, -1.39506327,
         0.60667898],
       [-1.0520469 ,  1.17572876,  1.45788525,  0.39067803,  1.07725164,
         1.43947028],
       [ 0.51816842, -1.41315494,  0.37348035,  0.84391135, -1.43002787,
         0.79696687],
       [ 0.11313671, -1.21697346, -0.29698226,  0.11842104,  2.04687897,
         1.42521716]])

In [6]:
#3
dataset.shape
dataset[212:222,:]

array([[ 0.83216384, -3.78697665,  1.94521478,  1.09893135, -4.30695985,
         0.86067322],
       [-0.66175704, -0.80575687,  0.01767358,  0.21816288, -0.84965584,
        -0.04115126],
       [-0.2140646 ,  0.94727919,  0.33345845,  0.8374127 , -0.86592565,
        -0.2884397 ],
       [-1.44238954,  0.59640134,  0.65600738,  0.27327203, -0.03109208,
         0.24304118],
       [-0.10312467,  0.62605768, -1.43526353,  0.57925647,  0.36074129,
         0.25642916],
       [-0.59851449,  1.19534596, -0.55339663,  1.34504259, -1.37909873,
         1.01356087],
       [ 0.3356252 ,  1.36121216, -0.83412562, -0.82638094,  1.80554678,
        -0.42855539],
       [-0.30567252, -1.00850113,  0.16828318,  0.84217855,  0.32498442,
        -0.53410072]])

In [7]:
#4
ds_aleat=dataset[np.random.choice(222),:]
for i in range(0,9):
    ds_aleat=np.vstack([ds_aleat,dataset[np.random.choice(222),:]])
ds_aleat

array([[-0.90284133, -1.7432147 ,  0.06534685, -0.54466821, -1.99416528,
        -0.46993397],
       [-0.27558749,  0.44375102, -1.19516358, -0.89731667,  0.38277255,
        -1.17108376],
       [-1.33525401,  0.86033443, -2.08102641, -0.76028626, -0.95064195,
        -1.5654989 ],
       [-0.03786009, -1.37182143, -1.15144051,  0.61648203,  0.27429176,
         1.69007885],
       [ 0.85308506, -1.14190568, -0.96012919, -0.3308694 , -1.20429361,
         0.51125543],
       [ 0.29412717, -0.82610067,  1.62868312, -0.36148233, -0.88224346,
        -0.06619606],
       [ 1.18749179,  0.58078448,  1.01383673, -1.00876055,  0.74927091,
         0.86203736],
       [-0.54540261, -1.02578627, -0.99325503, -0.3496903 ,  1.45131751,
         0.51389177],
       [-1.33525401,  0.86033443, -2.08102641, -0.76028626, -0.95064195,
        -1.5654989 ],
       [-0.20665015,  0.6977003 , -0.16806729, -0.90777396,  0.12750208,
         0.69151507]])

In [8]:
#5
dataset[149:160,2:5]

array([[ 0.26442272, -0.55642572, -0.98494904],
       [-0.16806729, -0.90777396,  0.12750208],
       [ 0.22265762,  0.61653699, -1.224038  ],
       [-0.54261257, -1.37785436, -0.74526702],
       [-0.08384223,  1.33934661,  0.64184796],
       [-0.64605458,  0.27357532,  0.42394969],
       [-0.57500875, -0.91039838,  2.85130635],
       [-0.57432942,  0.46871576,  0.75225653],
       [-1.45578956, -0.95467694, -2.16703977],
       [ 1.58718446, -0.82448574,  0.39597689],
       [-1.19516358, -0.89731667,  0.38277255]])

### Selección condicional

    6.Crea un nuevo subconjunto que solamente contenga las muestras que pertenecen a la clase 
    7.¿Cuántas muestras tenemos de esta clase?
    8.Selecciona todas filas cuyos valores de la tercera columna sean positivos

In [17]:
#6
ds_4=dataset[classes==3]
#7
ds_4.shape[0]

55

In [14]:
#8
ds_4pos=ds_4[ds_4[:,2]>0]

### Funciones de numpy
    09.Muestra el valor mínimo, el valor máximo y la media de cada columna.
    10.Guárdalo en una matriz de dimensiones 3x6
    11.Puedes programar una sentencia que nos diga cuál de las clases tiene el valor más alto? ** [Difícil] (El mayor màximo)

### Dibujando con Matplotlib
    12.Dibuja un diagrama de barras donde se vea el valor medio de cada clase. Este gráfico debe tener como mínimo un título e información en los ejes
    13.Dibuja un gráfico donde se pueda confrontar la primera característica (columna 0) con la quinta (columna 4). Serías capaz de asignar un color diferente a cada clase?
    14.Muestra en un gráfico de los valores de la columna 4 por cada observación. Añadele la columna 2
    15.No crees que sería mejor crear un histograma de los valores de la columna 4?

### Aprendizaje automático 
(ver Notebook del dataset de digits)

    16. Utiliza la técnica de aprendizaje de random forest para intentar clasificar este conjunto de características **

    17.Existe otra técnica llamada Máquinas de vectores de soporte (SVM). Intenta aplicar esta técnica, qué resultados obtienes?
   [Enlace](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html)